### ISSUE TITLE
Installation instructions unclear

### ISSUE THREAD

**Issue by WillsB3** [robjtede/alfred-caniuse#15]
Hi,

I'd like to try this workflow, and do not wish to use alfred-updater. The README says that the workflow can be downloaded from the releases page, however I can only see the source code archive on the releases page.

Am i missing something?

**Comment by robjtede** [comment]
No you are right, the latest release doesnt have the workflow uploaded as an asset. Personally don't use it since its a pain to reduce the bundle size to something reasonable.

**Comment by WillsB3** [comment]
> No you are right, the latest release doesnt have the workflow uploaded as an asset. Personally don't use it since its a pain to reduce the bundle size to something reasonable.

As in you don't use the packaged .alfredworkflow version? Is there a way to use this workflow with Alfred 4 without alfred-updater?

**Comment by robjtede** [comment]
> As in you don't use the packaged .alfredworkflow version?

Basically, yes.

In the short term, you could clone the repo and build it yourself.
